### ISSUE TITLE
Update README.MD

### ISSUE THREAD

**Issue by vikumkbv** [eSportlk/course-management-system#1]
Write a meaning full read me for this project

**Comment by bineetNaidu** [comment]
hey, would u like me to work in this issue :smile: . But it would be good if u give more info on this project

**Comment by vikumkbv** [comment]
@gigara will provide more information to you

**Comment by gigara** [comment]
@bineetNaidu Yes you can contribute. This is a opensource management system build with spring framework. There are 3 logins for admin student and lecturers. Lecturers can add lecture materials / meeting links and other stuff to the portal and students can submit their responses. Admin can add students and lecturers to the system and control the system. Zoom API will be used to integrate the online meeting feature.
